version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    restart: always
    networks:
      - app-network

  nextjs:
    build: .
    expose:
      - '3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
